### PR TITLE
Issue #2 

### PR DESCRIPTION
**Pull request by vitalpoltava**
Hi Jamund,

I selected issue #2:
1) Added a 'New' link on the right of the Deck's list;
2) On click above 'New' link user is referred to respective form ( see below);
3) After adding adding fields values and clicking 'Add Deck' button a new Deck is being created and a user redirects to new deck's page.

Working project is here http://slide-web.vitalpoltava.c9.io (but sometimes C9 switches Node process off, so if you want to review and it is not working - please let me know and I will switch it on).

-Vital

slides-web-form

### CODE REVIEW

**Comment by xjamundx** [comment]
Any chance you can you rebase this into a single commit? It's a lot easier to see that way! thanks!

**Comment by vitalpoltava** [comment]
Sorry for that. I will try to do it asap...

**Comment by xjamundx** [comment]
FYI, you'll likely need to push using -f (force) for it to work. No big
deal though!

**Comment by vitalpoltava** [comment]
I made a consolidated commit but git refuses to accept the new pull request. Maybe you know how to override this?

**Comment by xjamundx** [comment]
--force

**Comment by vitalpoltava** [comment]
I made a push to my branch. But after I tried to initiate a pull request, the warning appeared (see the screenshot below):
pull_request

**Pull request merged**
